### A Pluto.jl notebook ###
# v0.19.9

using Markdown
using InteractiveUtils

# ╔═╡ cfe47b92-f9a7-11ed-0b3b-7989d4f7dd80
using CSV, PlotlyJS, LinearAlgebra, Random, Distributions, PlutoUI

# ╔═╡ 24849576-9a21-4b1a-845f-7e20a97c6d42
import LinearAlgebra: norm, norm1, norm2

# ╔═╡ 7220a755-2ebf-4ed0-90b8-e619f3e571d0
PlutoUI.TableOfContents()

# ╔═╡ 7f2eee1f-a8ab-4b57-ae17-5c1a187baf60
# A couple of test utilities.
begin
	function isclose(a, b, prec=1.e-8)
		norm(a - b) < prec
	end
end

# ╔═╡ 15756b60-f69f-4097-86b9-bddf61bb13c9
begin

	md"""
	# Generalized Linear Models

	
	model (a) linear regression that uses an L2 regularizer
	model (b) linear regression that uses the ADAM optimizer
	
	the implementation of LR simply uses stochastic gradient descent (SGD), with a scalar fixed stepsize, with each update using only one sample $(\mathbf{x}_i, y_i)$ (rather than a larger mini-batch):
	
	$$\mathbf{w}_{t+1} = \mathbf{w}_t - \eta (f_{\mathbf{w}_t}(\mathbf{x}_i) - y_i) \mathbf{x}_i$$
	
	In the end, I showcase my own multinomial logistic regression
	"""
end

# ╔═╡ f3e95099-ed95-4657-aa0c-6b2d1f378222
begin
	md"""
	# Linear Regression
	"""
end

# ╔═╡ cf2e4792-12d9-43cd-ac8d-b587faebd0b1
begin
	md"""
	## Creating Synthetic Data

	First, lets create a synthetic dataset. The purpose being to create controlled situations for testing the methods. We can create synthetic datasets that match the assumptions underlying a method, and so test our implementations. If they do not behave as we expect, then this might indicate a bug (conceptually or in our code).
	
	The synthetic data has targets $y$ that are generated by sampling from a Gaussian where the mean is a linear function $f$ of $\mathbf{x}$ with some fixed variance $\sigma^2$.
	
	To create a synthetic dataset, we need to decide what distribution to use. I have preffered to generate these inputs randomly from Gaussians.
	
	"""
end

# ╔═╡ 1386bd89-a143-4084-981c-a77c76314455
num_samples = 30000

# ╔═╡ 04701d03-e8ff-4da1-8cf6-f77221785b0c
# Convenient to have number of features assigned to a variable
num_features = 15 + # base features 
	           1    # added column of ones

# ╔═╡ 95183b18-85ad-4460-b1bd-3199577a101f
"""
	generate_features(rng)

This function generates features according to a InverseGaussian distribution 
(μ = 0.1 and λ = 1).
"""
function generate_features(rng)
	μs = rand(rng, 10)
	X = reduce(hcat, [rand(rng, InverseGaussian(μs[i], 1), num_samples) for i in 1:10])

	# Now we can add some components which are linearly dependent
	X = hcat(X, 0.33*X[:, 1] .+  0.67*X[:, 5])
	X = hcat(X, -X[:, 4])
	X = hcat(X, X[:, 3] .- X[:, 8])
	X = hcat(X, X[:, 9] .+ 0.5*X[:, 10])
	X = hcat(X, X[:, 6] .- 0.5*X[:, 2])
	

	# let's also append a column of ones to act as a bias unit
	X = cat(X, ones(num_samples), dims=2)
	
	return X
end

# ╔═╡ 22709dd8-1426-46a8-af38-d1908d6333ca
md"
Below, we specify the linear function that we will use to generate the synthetic data. A few restrictions include:
1. Equation $f(x) = c$ for some constant $c$ cannot be permitted
2. Function $f(x)$ depends on at least 2 columns of $X$
3. function should be single variate (1 output)
"

# ╔═╡ d0f7c8ad-a7a1-4b8e-a8a5-5a1dabe30421
W_true = let
	w_temp = rand(Random.Xoshiro(10), Normal(0, 0.2), num_features, 1)
	w_temp
end

# ╔═╡ 065786f5-00a2-466b-b634-72b7aee33c18
# TODO: f should be a linear function, that uses the weights W_true
function f(X::AbstractMatrix)
	szc = size(X,2)
	szr = size(X,1)
	szc = 1
	output = 0
	szr = 5
	for t in (1:szc)
		the_weight = W_true[t,:][1]
		for j in (1:szr)
			new = X[j,:][szc] * the_weight
			output += new
		end
	end
	output
end

# ╔═╡ 931dd00b-88b3-475d-974f-9631e1c9f7f8
md"""Now we generate the data for the Linear models"""

# ╔═╡ cfba2459-ed50-4593-9249-bdc0916459e8
"""
	generate_targets(X::AbstractMatrix, rng::Random.AbstractRNG)

This function takes features `X` and a random number generate `rng` and returns the targets for our synthetic dataset. The targets are generated using the linear function `f(X)` plus noise sampled from a Normal distribution with μ = 0 and σ² = 1. 
"""
function generate_targets(X::AbstractMatrix, rng::Random.AbstractRNG)
	y = reduce(hcat, [rand(rng, Normal(f(X), 1), num_samples)])
	return y
end

# ╔═╡ edd48940-e2bb-4077-8ead-00035e357ba3
X, Y = let
	rng = Random.Xoshiro(39432)
	X = generate_features(rng)
	Y = generate_targets(X, rng)
	X, Y
end

# ╔═╡ 78a7766f-fb7b-43e0-8d0b-cd2ee88be239
md"
With a true random perturbation, we see an approximately normal distribution below.
"

# ╔═╡ 7ec0bbee-472d-4cf9-bc50-50623b9c903d
let
	trace = histogram(Dict(:x=>Y[:, 1]), kind="histogram")
	plt = Plot(trace)
	PlotlyJS.relayout(plt, height=400, showlegend=false)
end

# ╔═╡ bb36752d-8bee-4256-9342-c88f1a74148f
begin
	md"""
	## Linear Models
	
	We begin with a structure, a subclass of the Model type. Each subclass of Model is obligated to supply a predict function. This function accepts an instance of the model and a data matrix X as input, and subsequently returns a vector of predictions y.
	
	To modify the weights of an instance of a model, you are required to develop the update! function. This function requires the model instance, an optimizer, a data matrix of inputs, and a data vector of responses as input parameters.
	"""
end

# ╔═╡ 95538be2-4704-4093-bd42-86fa4938ccc9
begin
	RMSE(x̂, x) = norm2(x̂ .- x) # equivalent to norm(x̂ .- x, 2)
	L2Error = RMSE
	L1Error(x̂, x) = norm1(x̂ .- x)
end

# ╔═╡ 2339a5ae-c503-424c-9a63-ecefd07f77e7
begin
	# Create the shared parent type
	abstract type Model end

	# Create a placeholder for the `predict` function
	function predict end

	# Create a shared optimizer parent type
	abstract type Optimizer end
end

# ╔═╡ 2aa446f7-0f32-4621-b7dd-f33eca20fb6a
md"We then split our data into a train/test."

# ╔═╡ 6813a762-9fe4-478a-885c-4dcd83518995
begin
	trainX = X[1:25000, :]
	testX = X[25001:end, :]

	trainY = Y[1:25000, :]
	testY = Y[25001:end, :]
end;

# ╔═╡ 076572bd-d51f-4bee-9621-fc5efe28310e
begin
	md"""
	### Simple Linear Regression
	
	As mentioned above, this implementation of linear regression (LR) using stochastic gradient descent (SGD) with one sample.
	
	Steps:-
	
	i) For each epoch, dataset is randomly shuffled.
	
	ii) When iterated over in order, update for each sample $i$.
	
	iii) A fixed scalar stepsize is used, rather than adaptive vector stepsizes.
	
	We opted for a simpler implementation of linear regression, where we do not use mini-batches.
	"""
end

# ╔═╡ ebfa9645-3108-4f49-a6b9-a7d213a7d857
begin
	mutable struct LinearModel <: Model
		W::Matrix
	end

	# add a default initializer (all weights=0)
	LinearModel(in, out=1) = LinearModel(
		# initialize W
		zeros(in, out)
	)

	# For consistency with notes, define inner-product with column vectors
	predict(lm::LinearModel, x::AbstractVector) = x'*lm.W
	# and with matrices
	predict(lm::LinearModel, X::AbstractMatrix) = X*lm.W
end

# ╔═╡ 90a697fa-9c3a-4dd8-b686-6bd199d47d8b
struct SGD <: Optimizer
	α::Number
end

# ╔═╡ c0366d9c-84cd-446b-8238-9458f2f1f99d
md"We will set the number of epochs globally to be used by all the algorithms."

# ╔═╡ 4768b1e9-3105-4c2c-999c-696f26d5d816
NUM_EPOCHS = 10

# ╔═╡ 97bb7ff0-893c-41ac-8193-a94d9e274626
begin
	md"""
	### Regularized LR
	"""
end

# ╔═╡ bb82b077-dfad-4072-ac77-a8cce349e10a
md"
In this section, we implement linear regression with l2 regularization (RLR).
We modify the update rule for the linear regression solution given above to add l2 regularization. The update is

$$\mathbf{w}_{t+1} = \mathbf{w}_t - \eta (f_{\mathbf{w}_t}(\mathbf{x}_i) - y_i) \mathbf{x}_i - \eta \lambda  \mathbf{w}_t$$

"

# ╔═╡ a30993b1-b54f-4551-ad0d-90ad7e552f59
mutable struct RegularizedModel <: Model
	W::Matrix
	lambda::Number
	RegularizedModel(in::Int, out::Int, lambda::Number) = new(
		zeros(in, out),
		lambda
	)
end

# ╔═╡ b58c4563-67e2-4bb7-b4c9-8ced8646b88b
predict(m::RegularizedModel, x::AbstractVector) = x'*m.W

# ╔═╡ c3c7be23-3863-4d58-97c2-9c3270e11371
# for Matrices
predict(m::RegularizedModel, X::AbstractMatrix) = X*m.W

# ╔═╡ 6bbf8af3-5412-4d0b-a938-5e8f6040bd13
function update!(lm::LinearModel, sgd::SGD, x::AbstractVector, y::AbstractVector)
	ŷ = predict(lm, x)

	err = ŷ - y
	ΔW = err .* x
	lm.W .-= sgd.α * ΔW
end

# ╔═╡ 3622b3a0-fe41-4416-be2b-34aabd19c090
md"finally, we update"

# ╔═╡ 810e55b1-a1d4-4fcf-84ce-53133d32f853
function update!(lm::RegularizedModel, sgd::SGD, x::AbstractVector, y::AbstractVector)
	lm.W = lm.W - 
	(sgd.α * (predict(lm, x) - y)[1] * x ) - 
	(sgd.α * lm.lambda * lm.W)
end

# ╔═╡ 1519061d-c7e8-4510-aba5-3818a5500b43
function train!(m::Model, sgd::Optimizer, X::AbstractMatrix, Y::AbstractMatrix)
	# Random.seed!(1)
	rng = Random.MersenneTwister(1)
	for idx in randperm(rng, size(Y, 1))
		update!(m, sgd, X[idx, :], Y[idx, :])
	end
end

# ╔═╡ 0ae4fc65-e287-4da0-a4ba-fd3dbd4acefc
# use a function to avoid cluttering global scope with tmp variables
function runLinearModel(X::AbstractMatrix, Y::AbstractMatrix)
	# construct a model
	sgd = SGD(0.01)

	model = LinearModel(size(X, 2), 1)

	# Each call to train! performs a single epoch
	for _ in 1:NUM_EPOCHS
		train!(model, sgd, X, Y)
	end

	model
end

# ╔═╡ 2f48323b-953c-4b8b-9a47-ba53f1d654be
__linear_model = runLinearModel(trainX, trainY);

# ╔═╡ 59feaf32-e928-472d-b0a2-a5762dce6adb
RMSE(predict(__linear_model, testX), testY)

# ╔═╡ 5826f61d-f0b1-4210-8a45-978bd2054585
md"Now we train a regularized model λ = 1.0 for the synthetic dataset with SGD α=0.01."

# ╔═╡ 28a12e31-8713-436d-a344-f2a7db9f3c07
function runRLRModel(X::AbstractMatrix, Y::AbstractMatrix)
	# train
	sgd = SGD(0.01)

	model = RegularizedModel(size(X, 2), 1, 1.0)

	for _ in 1:NUM_EPOCHS
		train!(model, sgd, X, Y)
	end

	model
end

# ╔═╡ d17e8dc4-c73e-430e-8807-82bb8d6339e5
__rlr_model = runRLRModel(trainX, trainY);

# ╔═╡ 2c7a5be1-1fcc-47a3-ba47-da49d7306c3b
RMSE(predict(__rlr_model, testX), testY)

# ╔═╡ 00000000-0000-0000-0000-000000000001
PLUTO_PROJECT_TOML_CONTENTS = """
[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
CSV = "~0.10.10"
Distributions = "~0.25.94"
PlotlyJS = "~0.18.10"
PlutoUI = "~0.7.51"
"""

# ╔═╡ 00000000-0000-0000-0000-000000000002
PLUTO_MANIFEST_TOML_CONTENTS = """
# This file is machine-generated - editing it directly is not advised

julia_version = "1.8.1"
manifest_format = "2.0"
project_hash = "0010744dbafd6f008b447808d273c9bf3df65bbe"

[[deps.AbstractPlutoDingetjes]]
deps = ["Pkg"]
git-tree-sha1 = "8eaf9f1b4921132a4cff3f36a1d9ba923b14a481"
uuid = "6e696c72-6542-2067-7265-42206c756150"
version = "1.1.4"

[[deps.ArgTools]]
uuid = "0dad84c5-d112-42e6-8d28-ef12dabb789f"
version = "1.1.1"

[[deps.Artifacts]]
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[[deps.AssetRegistry]]
deps = ["Distributed", "JSON", "Pidfile", "SHA", "Test"]
git-tree-sha1 = "b25e88db7944f98789130d7b503276bc34bc098e"
uuid = "bf4720bc-e11a-5d0c-854e-bdca1663c893"
version = "0.1.0"

[[deps.Base64]]
uuid = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"

[[deps.BinDeps]]
deps = ["Libdl", "Pkg", "SHA", "URIParser", "Unicode"]
git-tree-sha1 = "1289b57e8cf019aede076edab0587eb9644175bd"
uuid = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
version = "1.0.2"

[[deps.Blink]]
deps = ["Base64", "BinDeps", "Distributed", "JSExpr", "JSON", "Lazy", "Logging", "MacroTools", "Mustache", "Mux", "Reexport", "Sockets", "WebIO", "WebSockets"]
git-tree-sha1 = "08d0b679fd7caa49e2bca9214b131289e19808c0"
uuid = "ad839575-38b3-5650-b840-f874b8c74a25"
version = "0.12.5"

[[deps.CSV]]
deps = ["CodecZlib", "Dates", "FilePathsBase", "InlineStrings", "Mmap", "Parsers", "PooledArrays", "PrecompileTools", "SentinelArrays", "Tables", "Unicode", "WeakRefStrings", "WorkerUtilities"]
git-tree-sha1 = "ed28c86cbde3dc3f53cf76643c2e9bc11d56acc7"
uuid = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
version = "0.10.10"

[[deps.Calculus]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "f641eb0a4f00c343bbc32346e1217b86f3ce9dad"
uuid = "49dc2e85-a5d0-5ad3-a950-438e2897f1b9"
version = "0.5.1"

[[deps.ChainRulesCore]]
deps = ["Compat", "LinearAlgebra", "SparseArrays"]
git-tree-sha1 = "e30f2f4e20f7f186dc36529910beaedc60cfa644"
uuid = "d360d2e6-b24c-11e9-a2a3-2a2ae2dbcce4"
version = "1.16.0"

[[deps.ChangesOfVariables]]
deps = ["LinearAlgebra", "Test"]
git-tree-sha1 = "f84967c4497e0e1955f9a582c232b02847c5f589"
uuid = "9e997f8a-9a97-42d5-a9f1-ce6bfc15e2c0"
version = "0.1.7"

[[deps.CodecZlib]]
deps = ["TranscodingStreams", "Zlib_jll"]
git-tree-sha1 = "9c209fb7536406834aa938fb149964b985de6c83"
uuid = "944b1d66-785c-5afd-91f1-9de20f533193"
version = "0.7.1"

[[deps.ColorSchemes]]
deps = ["ColorTypes", "ColorVectorSpace", "Colors", "FixedPointNumbers", "PrecompileTools", "Random"]
git-tree-sha1 = "be6ab11021cd29f0344d5c4357b163af05a48cba"
uuid = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
version = "3.21.0"

[[deps.ColorTypes]]
deps = ["FixedPointNumbers", "Random"]
git-tree-sha1 = "eb7f0f8307f71fac7c606984ea5fb2817275d6e4"
uuid = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
version = "0.11.4"

[[deps.ColorVectorSpace]]
deps = ["ColorTypes", "FixedPointNumbers", "LinearAlgebra", "SpecialFunctions", "Statistics", "TensorCore"]
git-tree-sha1 = "600cc5508d66b78aae350f7accdb58763ac18589"
uuid = "c3611d14-8923-5661-9e6a-0046d554d3a4"
version = "0.9.10"

[[deps.Colors]]
deps = ["ColorTypes", "FixedPointNumbers", "Reexport"]
git-tree-sha1 = "fc08e5930ee9a4e03f84bfb5211cb54e7769758a"
uuid = "5ae59095-9a9b-59fe-a467-6f913c188581"
version = "0.12.10"

[[deps.Compat]]
deps = ["Dates", "LinearAlgebra", "UUIDs"]
git-tree-sha1 = "7a60c856b9fa189eb34f5f8a6f6b5529b7942957"
uuid = "34da2185-b29b-5c13-b0c7-acf172513d20"
version = "4.6.1"

[[deps.CompilerSupportLibraries_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "e66e0078-7015-5450-92f7-15fbd957f2ae"
version = "0.5.2+0"

[[deps.DataAPI]]
git-tree-sha1 = "8da84edb865b0b5b0100c0666a9bc9a0b71c553c"
uuid = "9a962f9c-6df0-11e9-0e5d-c546b8b5ee8a"
version = "1.15.0"

[[deps.DataStructures]]
deps = ["Compat", "InteractiveUtils", "OrderedCollections"]
git-tree-sha1 = "d1fff3a548102f48987a52a2e0d114fa97d730f0"
uuid = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
version = "0.18.13"

[[deps.DataValueInterfaces]]
git-tree-sha1 = "bfc1187b79289637fa0ef6d4436ebdfe6905cbd6"
uuid = "e2d170a0-9d28-54be-80f0-106bbe20a464"
version = "1.0.0"

[[deps.Dates]]
deps = ["Printf"]
uuid = "ade2ca70-3891-5945-98fb-dc099432e06a"

[[deps.DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[deps.DensityInterface]]
deps = ["InverseFunctions", "Test"]
git-tree-sha1 = "80c3e8639e3353e5d2912fb3a1916b8455e2494b"
uuid = "b429d917-457f-4dbc-8f4c-0cc954292b1d"
version = "0.4.0"

[[deps.Distributed]]
deps = ["Random", "Serialization", "Sockets"]
uuid = "8ba89e20-285c-5b6f-9357-94700520ee1b"

[[deps.Distributions]]
deps = ["ChainRulesCore", "DensityInterface", "FillArrays", "LinearAlgebra", "PDMats", "Printf", "QuadGK", "Random", "SparseArrays", "SpecialFunctions", "Statistics", "StatsAPI", "StatsBase", "StatsFuns", "Test"]
git-tree-sha1 = "aa8ae1e8e8d4b5ef38a8fbc028fc75f3c5cad73d"
uuid = "31c24e10-a181-5473-b8eb-7969acd0382f"
version = "0.25.94"

[[deps.DocStringExtensions]]
deps = ["LibGit2"]
git-tree-sha1 = "2fb1e02f2b635d0845df5d7c167fec4dd739b00d"
uuid = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
version = "0.9.3"

[[deps.Downloads]]
deps = ["ArgTools", "FileWatching", "LibCURL", "NetworkOptions"]
uuid = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
version = "1.6.0"

[[deps.DualNumbers]]
deps = ["Calculus", "NaNMath", "SpecialFunctions"]
git-tree-sha1 = "5837a837389fccf076445fce071c8ddaea35a566"
uuid = "fa6b7ba4-c1ee-5f82-b5fc-ecf0adba8f74"
version = "0.6.8"

[[deps.FilePathsBase]]
deps = ["Compat", "Dates", "Mmap", "Printf", "Test", "UUIDs"]
git-tree-sha1 = "e27c4ebe80e8699540f2d6c805cc12203b614f12"
uuid = "48062228-2e41-5def-b9a4-89aafe57970f"
version = "0.9.20"

[[deps.FileWatching]]
uuid = "7b1f6079-737a-58dc-b8bc-7a2ca5c1b5ee"

[[deps.FillArrays]]
deps = ["LinearAlgebra", "Random", "SparseArrays", "Statistics"]
git-tree-sha1 = "fa10570aee20250d446c9951b459c63529b1107c"
uuid = "1a297f60-69ca-5386-bcde-b61e274b549b"
version = "1.0.2"

[[deps.FixedPointNumbers]]
deps = ["Statistics"]
git-tree-sha1 = "335bfdceacc84c5cdf16aadc768aa5ddfc5383cc"
uuid = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
version = "0.8.4"

[[deps.FunctionalCollections]]
deps = ["Test"]
git-tree-sha1 = "04cb9cfaa6ba5311973994fe3496ddec19b6292a"
uuid = "de31a74c-ac4f-5751-b3fd-e18cd04993ca"
version = "0.5.0"

[[deps.Future]]
deps = ["Random"]
uuid = "9fa8497b-333b-5362-9e8d-4d0656e87820"

[[deps.HTTP]]
deps = ["Base64", "Dates", "IniFile", "Logging", "MbedTLS", "NetworkOptions", "Sockets", "URIs"]
git-tree-sha1 = "0fa77022fe4b511826b39c894c90daf5fce3334a"
uuid = "cd3eb016-35fb-5094-929b-558a96fad6f3"
version = "0.9.17"

[[deps.Hiccup]]
deps = ["MacroTools", "Test"]
git-tree-sha1 = "6187bb2d5fcbb2007c39e7ac53308b0d371124bd"
uuid = "9fb69e20-1954-56bb-a84f-559cc56a8ff7"
version = "0.2.2"

[[deps.HypergeometricFunctions]]
deps = ["DualNumbers", "LinearAlgebra", "OpenLibm_jll", "SpecialFunctions"]
git-tree-sha1 = "84204eae2dd237500835990bcade263e27674a93"
uuid = "34004b35-14d8-5ef3-9330-4cdb6864b03a"
version = "0.3.16"

[[deps.Hyperscript]]
deps = ["Test"]
git-tree-sha1 = "8d511d5b81240fc8e6802386302675bdf47737b9"
uuid = "47d2ed2b-36de-50cf-bf87-49c2cf4b8b91"
version = "0.0.4"

[[deps.HypertextLiteral]]
deps = ["Tricks"]
git-tree-sha1 = "c47c5fa4c5308f27ccaac35504858d8914e102f9"
uuid = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
version = "0.9.4"

[[deps.IOCapture]]
deps = ["Logging", "Random"]
git-tree-sha1 = "d75853a0bdbfb1ac815478bacd89cd27b550ace6"
uuid = "b5f81e59-6552-4d32-b1f0-c071b021bf89"
version = "0.2.3"

[[deps.IniFile]]
git-tree-sha1 = "f550e6e32074c939295eb5ea6de31849ac2c9625"
uuid = "83e8ac13-25f8-5344-8a64-a9f2b223428f"
version = "0.5.1"

[[deps.InlineStrings]]
deps = ["Parsers"]
git-tree-sha1 = "9cc2baf75c6d09f9da536ddf58eb2f29dedaf461"
uuid = "842dd82b-1e85-43dc-bf29-5d0ee9dffc48"
version = "1.4.0"

[[deps.InteractiveUtils]]
deps = ["Markdown"]
uuid = "b77e0a4c-d291-57a0-90e8-8db25a27a240"

[[deps.InverseFunctions]]
deps = ["Test"]
git-tree-sha1 = "6667aadd1cdee2c6cd068128b3d226ebc4fb0c67"
uuid = "3587e190-3f89-42d0-90ee-14403ec27112"
version = "0.1.9"

[[deps.IrrationalConstants]]
git-tree-sha1 = "630b497eafcc20001bba38a4651b327dcfc491d2"
uuid = "92d709cd-6900-40b7-9082-c6be49f344b6"
version = "0.2.2"

[[deps.IteratorInterfaceExtensions]]
git-tree-sha1 = "a3f24677c21f5bbe9d2a714f95dcd58337fb2856"
uuid = "82899510-4779-5014-852e-03e436cf321d"
version = "1.0.0"

[[deps.JLLWrappers]]
deps = ["Preferences"]
git-tree-sha1 = "abc9885a7ca2052a736a600f7fa66209f96506e1"
uuid = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
version = "1.4.1"

[[deps.JSExpr]]
deps = ["JSON", "MacroTools", "Observables", "WebIO"]
git-tree-sha1 = "b413a73785b98474d8af24fd4c8a975e31df3658"
uuid = "97c1335a-c9c5-57fe-bc5d-ec35cebe8660"
version = "0.5.4"

[[deps.JSON]]
deps = ["Dates", "Mmap", "Parsers", "Unicode"]
git-tree-sha1 = "31e996f0a15c7b280ba9f76636b3ff9e2ae58c9a"
uuid = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
version = "0.21.4"

[[deps.Kaleido_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "43032da5832754f58d14a91ffbe86d5f176acda9"
uuid = "f7e6163d-2fa5-5f23-b69c-1db539e41963"
version = "0.2.1+0"

[[deps.LaTeXStrings]]
git-tree-sha1 = "f2355693d6778a178ade15952b7ac47a4ff97996"
uuid = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
version = "1.3.0"

[[deps.Lazy]]
deps = ["MacroTools"]
git-tree-sha1 = "1370f8202dac30758f3c345f9909b97f53d87d3f"
uuid = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
version = "0.15.1"

[[deps.LibCURL]]
deps = ["LibCURL_jll", "MozillaCACerts_jll"]
uuid = "b27032c2-a3e7-50c8-80cd-2d36dbcbfd21"
version = "0.6.3"

[[deps.LibCURL_jll]]
deps = ["Artifacts", "LibSSH2_jll", "Libdl", "MbedTLS_jll", "Zlib_jll", "nghttp2_jll"]
uuid = "deac9b47-8bc7-5906-a0fe-35ac56dc84c0"
version = "7.84.0+0"

[[deps.LibGit2]]
deps = ["Base64", "NetworkOptions", "Printf", "SHA"]
uuid = "76f85450-5226-5b5a-8eaa-529ad045b433"

[[deps.LibSSH2_jll]]
deps = ["Artifacts", "Libdl", "MbedTLS_jll"]
uuid = "29816b5a-b9ab-546f-933c-edad1886dfa8"
version = "1.10.2+0"

[[deps.Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[deps.LinearAlgebra]]
deps = ["Libdl", "libblastrampoline_jll"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[deps.LogExpFunctions]]
deps = ["ChainRulesCore", "ChangesOfVariables", "DocStringExtensions", "InverseFunctions", "IrrationalConstants", "LinearAlgebra"]
git-tree-sha1 = "0a1b7c2863e44523180fdb3146534e265a91870b"
uuid = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
version = "0.3.23"

[[deps.Logging]]
uuid = "56ddb016-857b-54e1-b83d-db4d58db5568"

[[deps.MIMEs]]
git-tree-sha1 = "65f28ad4b594aebe22157d6fac869786a255b7eb"
uuid = "6c6e2e6c-3030-632d-7369-2d6c69616d65"
version = "0.1.4"

[[deps.MacroTools]]
deps = ["Markdown", "Random"]
git-tree-sha1 = "42324d08725e200c23d4dfb549e0d5d89dede2d2"
uuid = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
version = "0.5.10"

[[deps.Markdown]]
deps = ["Base64"]
uuid = "d6f4376e-aef5-505a-96c1-9c027394607a"

[[deps.MbedTLS]]
deps = ["Dates", "MbedTLS_jll", "MozillaCACerts_jll", "Random", "Sockets"]
git-tree-sha1 = "03a9b9718f5682ecb107ac9f7308991db4ce395b"
uuid = "739be429-bea8-5141-9913-cc70e7f3736d"
version = "1.1.7"

[[deps.MbedTLS_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "c8ffd9c3-330d-5841-b78e-0817d7145fa1"
version = "2.28.0+0"

[[deps.Missings]]
deps = ["DataAPI"]
git-tree-sha1 = "f66bdc5de519e8f8ae43bdc598782d35a25b1272"
uuid = "e1d29d7a-bbdc-5cf2-9ac0-f12de2c33e28"
version = "1.1.0"

[[deps.Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"

[[deps.MozillaCACerts_jll]]
uuid = "14a3606d-f60d-562e-9121-12d972cd8159"
version = "2022.2.1"

[[deps.Mustache]]
deps = ["Printf", "Tables"]
git-tree-sha1 = "87c371d27dbf2449a5685652ab322be163269df0"
uuid = "ffc61752-8dc7-55ee-8c37-f3e9cdd09e70"
version = "1.0.15"

[[deps.Mux]]
deps = ["AssetRegistry", "Base64", "HTTP", "Hiccup", "Pkg", "Sockets", "WebSockets"]
git-tree-sha1 = "82dfb2cead9895e10ee1b0ca37a01088456c4364"
uuid = "a975b10e-0019-58db-a62f-e48ff68538c9"
version = "0.7.6"

[[deps.NaNMath]]
deps = ["OpenLibm_jll"]
git-tree-sha1 = "0877504529a3e5c3343c6f8b4c0381e57e4387e4"
uuid = "77ba4419-2d1f-58cd-9bb1-8ffee604a2e3"
version = "1.0.2"

[[deps.NetworkOptions]]
uuid = "ca575930-c2e3-43a9-ace4-1e988b2c1908"
version = "1.2.0"

[[deps.Observables]]
git-tree-sha1 = "6862738f9796b3edc1c09d0890afce4eca9e7e93"
uuid = "510215fc-4207-5dde-b226-833fc4488ee2"
version = "0.5.4"

[[deps.OpenBLAS_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "Libdl"]
uuid = "4536629a-c528-5b80-bd46-f80d51c5b363"
version = "0.3.20+0"

[[deps.OpenLibm_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "05823500-19ac-5b8b-9628-191a04bc5112"
version = "0.8.1+0"

[[deps.OpenSpecFun_jll]]
deps = ["Artifacts", "CompilerSupportLibraries_jll", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "13652491f6856acfd2db29360e1bbcd4565d04f1"
uuid = "efe28fd5-8261-553b-a9e1-b2916fc3738e"
version = "0.5.5+0"

[[deps.OrderedCollections]]
git-tree-sha1 = "d321bf2de576bf25ec4d3e4360faca399afca282"
uuid = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
version = "1.6.0"

[[deps.PDMats]]
deps = ["LinearAlgebra", "SparseArrays", "SuiteSparse"]
git-tree-sha1 = "67eae2738d63117a196f497d7db789821bce61d1"
uuid = "90014a1f-27ba-587c-ab20-58faa44d9150"
version = "0.11.17"

[[deps.Parameters]]
deps = ["OrderedCollections", "UnPack"]
git-tree-sha1 = "34c0e9ad262e5f7fc75b10a9952ca7692cfc5fbe"
uuid = "d96e819e-fc66-5662-9728-84c9c7592b0a"
version = "0.12.3"

[[deps.Parsers]]
deps = ["Dates", "PrecompileTools", "UUIDs"]
git-tree-sha1 = "a5aef8d4a6e8d81f171b2bd4be5265b01384c74c"
uuid = "69de0a69-1ddd-5017-9359-2bf0b02dc9f0"
version = "2.5.10"

[[deps.Pidfile]]
deps = ["FileWatching", "Test"]
git-tree-sha1 = "2d8aaf8ee10df53d0dfb9b8ee44ae7c04ced2b03"
uuid = "fa939f87-e72e-5be4-a000-7fc836dbe307"
version = "1.3.0"

[[deps.Pkg]]
deps = ["Artifacts", "Dates", "Downloads", "LibGit2", "Libdl", "Logging", "Markdown", "Printf", "REPL", "Random", "SHA", "Serialization", "TOML", "Tar", "UUIDs", "p7zip_jll"]
uuid = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
version = "1.8.0"

[[deps.PlotlyBase]]
deps = ["ColorSchemes", "Dates", "DelimitedFiles", "DocStringExtensions", "JSON", "LaTeXStrings", "Logging", "Parameters", "Pkg", "REPL", "Requires", "Statistics", "UUIDs"]
git-tree-sha1 = "56baf69781fc5e61607c3e46227ab17f7040ffa2"
uuid = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
version = "0.8.19"

[[deps.PlotlyJS]]
deps = ["Base64", "Blink", "DelimitedFiles", "JSExpr", "JSON", "Kaleido_jll", "Markdown", "Pkg", "PlotlyBase", "REPL", "Reexport", "Requires", "WebIO"]
git-tree-sha1 = "7452869933cd5af22f59557390674e8679ab2338"
uuid = "f0f68f2c-4968-5e81-91da-67840de0976a"
version = "0.18.10"

[[deps.PlutoUI]]
deps = ["AbstractPlutoDingetjes", "Base64", "ColorTypes", "Dates", "FixedPointNumbers", "Hyperscript", "HypertextLiteral", "IOCapture", "InteractiveUtils", "JSON", "Logging", "MIMEs", "Markdown", "Random", "Reexport", "URIs", "UUIDs"]
git-tree-sha1 = "b478a748be27bd2f2c73a7690da219d0844db305"
uuid = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
version = "0.7.51"

[[deps.PooledArrays]]
deps = ["DataAPI", "Future"]
git-tree-sha1 = "a6062fe4063cdafe78f4a0a81cfffb89721b30e7"
uuid = "2dfb63ee-cc39-5dd5-95bd-886bf059d720"
version = "1.4.2"

[[deps.PrecompileTools]]
deps = ["Preferences"]
git-tree-sha1 = "259e206946c293698122f63e2b513a7c99a244e8"
uuid = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
version = "1.1.1"

[[deps.Preferences]]
deps = ["TOML"]
git-tree-sha1 = "7eb1686b4f04b82f96ed7a4ea5890a4f0c7a09f1"
uuid = "21216c6a-2e73-6563-6e65-726566657250"
version = "1.4.0"

[[deps.Printf]]
deps = ["Unicode"]
uuid = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[[deps.QuadGK]]
deps = ["DataStructures", "LinearAlgebra"]
git-tree-sha1 = "6ec7ac8412e83d57e313393220879ede1740f9ee"
uuid = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
version = "2.8.2"

[[deps.REPL]]
deps = ["InteractiveUtils", "Markdown", "Sockets", "Unicode"]
uuid = "3fa0cd96-eef1-5676-8a61-b3b8758bbffb"

[[deps.Random]]
deps = ["SHA", "Serialization"]
uuid = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[[deps.Reexport]]
git-tree-sha1 = "45e428421666073eab6f2da5c9d310d99bb12f9b"
uuid = "189a3867-3050-52da-a836-e630ba90ab69"
version = "1.2.2"

[[deps.Requires]]
deps = ["UUIDs"]
git-tree-sha1 = "838a3a4188e2ded87a4f9f184b4b0d78a1e91cb7"
uuid = "ae029012-a4dd-5104-9daa-d747884805df"
version = "1.3.0"

[[deps.Rmath]]
deps = ["Random", "Rmath_jll"]
git-tree-sha1 = "f65dcb5fa46aee0cf9ed6274ccbd597adc49aa7b"
uuid = "79098fc4-a85e-5d69-aa6a-4863f24498fa"
version = "0.7.1"

[[deps.Rmath_jll]]
deps = ["Artifacts", "JLLWrappers", "Libdl", "Pkg"]
git-tree-sha1 = "6ed52fdd3382cf21947b15e8870ac0ddbff736da"
uuid = "f50d1b31-88e8-58de-be2c-1cc44531875f"
version = "0.4.0+0"

[[deps.SHA]]
uuid = "ea8e919c-243c-51af-8825-aaa63cd721ce"
version = "0.7.0"

[[deps.SentinelArrays]]
deps = ["Dates", "Random"]
git-tree-sha1 = "77d3c4726515dca71f6d80fbb5e251088defe305"
uuid = "91c51154-3ec4-41a3-a24f-3f23e20d615c"
version = "1.3.18"

[[deps.Serialization]]
uuid = "9e88b42a-f829-5b0c-bbe9-9e923198166b"

[[deps.Sockets]]
uuid = "6462fe0b-24de-5631-8697-dd941f90decc"

[[deps.SortingAlgorithms]]
deps = ["DataStructures"]
git-tree-sha1 = "a4ada03f999bd01b3a25dcaa30b2d929fe537e00"
uuid = "a2af1166-a08f-5f64-846c-94a0d3cef48c"
version = "1.1.0"

[[deps.SparseArrays]]
deps = ["LinearAlgebra", "Random"]
uuid = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[[deps.SpecialFunctions]]
deps = ["ChainRulesCore", "IrrationalConstants", "LogExpFunctions", "OpenLibm_jll", "OpenSpecFun_jll"]
git-tree-sha1 = "ef28127915f4229c971eb43f3fc075dd3fe91880"
uuid = "276daf66-3868-5448-9aa4-cd146d93841b"
version = "2.2.0"

[[deps.Statistics]]
deps = ["LinearAlgebra", "SparseArrays"]
uuid = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[[deps.StatsAPI]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "45a7769a04a3cf80da1c1c7c60caf932e6f4c9f7"
uuid = "82ae8749-77ed-4fe6-ae5f-f523153014b0"
version = "1.6.0"

[[deps.StatsBase]]
deps = ["DataAPI", "DataStructures", "LinearAlgebra", "LogExpFunctions", "Missings", "Printf", "Random", "SortingAlgorithms", "SparseArrays", "Statistics", "StatsAPI"]
git-tree-sha1 = "75ebe04c5bed70b91614d684259b661c9e6274a4"
uuid = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
version = "0.34.0"

[[deps.StatsFuns]]
deps = ["ChainRulesCore", "HypergeometricFunctions", "InverseFunctions", "IrrationalConstants", "LogExpFunctions", "Reexport", "Rmath", "SpecialFunctions"]
git-tree-sha1 = "f625d686d5a88bcd2b15cd81f18f98186fdc0c9a"
uuid = "4c63d2b9-4356-54db-8cca-17b64c39e42c"
version = "1.3.0"

[[deps.SuiteSparse]]
deps = ["Libdl", "LinearAlgebra", "Serialization", "SparseArrays"]
uuid = "4607b0f0-06f3-5cda-b6b1-a6196a1729e9"

[[deps.TOML]]
deps = ["Dates"]
uuid = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
version = "1.0.0"

[[deps.TableTraits]]
deps = ["IteratorInterfaceExtensions"]
git-tree-sha1 = "c06b2f539df1c6efa794486abfb6ed2022561a39"
uuid = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
version = "1.0.1"

[[deps.Tables]]
deps = ["DataAPI", "DataValueInterfaces", "IteratorInterfaceExtensions", "LinearAlgebra", "OrderedCollections", "TableTraits", "Test"]
git-tree-sha1 = "1544b926975372da01227b382066ab70e574a3ec"
uuid = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
version = "1.10.1"

[[deps.Tar]]
deps = ["ArgTools", "SHA"]
uuid = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
version = "1.10.0"

[[deps.TensorCore]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "1feb45f88d133a655e001435632f019a9a1bcdb6"
uuid = "62fd8b95-f654-4bbd-a8a5-9c27f68ccd50"
version = "0.1.1"

[[deps.Test]]
deps = ["InteractiveUtils", "Logging", "Random", "Serialization"]
uuid = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[[deps.TranscodingStreams]]
deps = ["Random", "Test"]
git-tree-sha1 = "9a6ae7ed916312b41236fcef7e0af564ef934769"
uuid = "3bb67fe8-82b1-5028-8e26-92a6c54297fa"
version = "0.9.13"

[[deps.Tricks]]
git-tree-sha1 = "aadb748be58b492045b4f56166b5188aa63ce549"
uuid = "410a4b4d-49e4-4fbc-ab6d-cb71b17b3775"
version = "0.1.7"

[[deps.URIParser]]
deps = ["Unicode"]
git-tree-sha1 = "53a9f49546b8d2dd2e688d216421d050c9a31d0d"
uuid = "30578b45-9adc-5946-b283-645ec420af67"
version = "0.4.1"

[[deps.URIs]]
git-tree-sha1 = "074f993b0ca030848b897beff716d93aca60f06a"
uuid = "5c2747f8-b7ea-4ff2-ba2e-563bfd36b1d4"
version = "1.4.2"

[[deps.UUIDs]]
deps = ["Random", "SHA"]
uuid = "cf7118a7-6976-5b1a-9a39-7adc72f591a4"

[[deps.UnPack]]
git-tree-sha1 = "387c1f73762231e86e0c9c5443ce3b4a0a9a0c2b"
uuid = "3a884ed6-31ef-47d7-9d2a-63182c4928ed"
version = "1.0.2"

[[deps.Unicode]]
uuid = "4ec0a83e-493e-50e2-b9ac-8f72acf5a8f5"

[[deps.WeakRefStrings]]
deps = ["DataAPI", "InlineStrings", "Parsers"]
git-tree-sha1 = "b1be2855ed9ed8eac54e5caff2afcdb442d52c23"
uuid = "ea10d353-3f73-51f8-a26c-33c1cb351aa5"
version = "1.4.2"

[[deps.WebIO]]
deps = ["AssetRegistry", "Base64", "Distributed", "FunctionalCollections", "JSON", "Logging", "Observables", "Pkg", "Random", "Requires", "Sockets", "UUIDs", "WebSockets", "Widgets"]
git-tree-sha1 = "976d0738247f155d0dcd77607edea644f069e1e9"
uuid = "0f1e0344-ec1d-5b48-a673-e5cf874b6c29"
version = "0.8.20"

[[deps.WebSockets]]
deps = ["Base64", "Dates", "HTTP", "Logging", "Sockets"]
git-tree-sha1 = "f91a602e25fe6b89afc93cf02a4ae18ee9384ce3"
uuid = "104b5d7c-a370-577a-8038-80a2059c5097"
version = "1.5.9"

[[deps.Widgets]]
deps = ["Colors", "Dates", "Observables", "OrderedCollections"]
git-tree-sha1 = "fcdae142c1cfc7d89de2d11e08721d0f2f86c98a"
uuid = "cc8bc4a8-27d6-5769-a93b-9d913e69aa62"
version = "0.6.6"

[[deps.WorkerUtilities]]
git-tree-sha1 = "cd1659ba0d57b71a464a29e64dbc67cfe83d54e7"
uuid = "76eceee3-57b5-4d4a-8e66-0e911cebbf60"
version = "1.6.1"

[[deps.Zlib_jll]]
deps = ["Libdl"]
uuid = "83775a58-1f1d-513f-b197-d71354ab007a"
version = "1.2.12+3"

[[deps.libblastrampoline_jll]]
deps = ["Artifacts", "Libdl", "OpenBLAS_jll"]
uuid = "8e850b90-86db-534c-a0d3-1478176c7d93"
version = "5.1.1+0"

[[deps.nghttp2_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "8e850ede-7688-5339-a07c-302acd2aaf8d"
version = "1.48.0+0"

[[deps.p7zip_jll]]
deps = ["Artifacts", "Libdl"]
uuid = "3f19e933-33d8-53b3-aaab-bd5110c3b7a0"
version = "17.4.0+0"
"""

# ╔═╡ Cell order:
# ╠═cfe47b92-f9a7-11ed-0b3b-7989d4f7dd80
# ╠═24849576-9a21-4b1a-845f-7e20a97c6d42
# ╠═7220a755-2ebf-4ed0-90b8-e619f3e571d0
# ╟─7f2eee1f-a8ab-4b57-ae17-5c1a187baf60
# ╟─15756b60-f69f-4097-86b9-bddf61bb13c9
# ╟─f3e95099-ed95-4657-aa0c-6b2d1f378222
# ╟─cf2e4792-12d9-43cd-ac8d-b587faebd0b1
# ╟─1386bd89-a143-4084-981c-a77c76314455
# ╟─04701d03-e8ff-4da1-8cf6-f77221785b0c
# ╟─95183b18-85ad-4460-b1bd-3199577a101f
# ╟─22709dd8-1426-46a8-af38-d1908d6333ca
# ╟─d0f7c8ad-a7a1-4b8e-a8a5-5a1dabe30421
# ╟─065786f5-00a2-466b-b634-72b7aee33c18
# ╟─931dd00b-88b3-475d-974f-9631e1c9f7f8
# ╟─cfba2459-ed50-4593-9249-bdc0916459e8
# ╟─edd48940-e2bb-4077-8ead-00035e357ba3
# ╟─78a7766f-fb7b-43e0-8d0b-cd2ee88be239
# ╟─7ec0bbee-472d-4cf9-bc50-50623b9c903d
# ╟─bb36752d-8bee-4256-9342-c88f1a74148f
# ╟─95538be2-4704-4093-bd42-86fa4938ccc9
# ╠═2339a5ae-c503-424c-9a63-ecefd07f77e7
# ╟─2aa446f7-0f32-4621-b7dd-f33eca20fb6a
# ╟─6813a762-9fe4-478a-885c-4dcd83518995
# ╟─076572bd-d51f-4bee-9621-fc5efe28310e
# ╟─ebfa9645-3108-4f49-a6b9-a7d213a7d857
# ╠═90a697fa-9c3a-4dd8-b686-6bd199d47d8b
# ╠═6bbf8af3-5412-4d0b-a938-5e8f6040bd13
# ╠═1519061d-c7e8-4510-aba5-3818a5500b43
# ╟─c0366d9c-84cd-446b-8238-9458f2f1f99d
# ╟─4768b1e9-3105-4c2c-999c-696f26d5d816
# ╠═0ae4fc65-e287-4da0-a4ba-fd3dbd4acefc
# ╠═2f48323b-953c-4b8b-9a47-ba53f1d654be
# ╠═59feaf32-e928-472d-b0a2-a5762dce6adb
# ╟─97bb7ff0-893c-41ac-8193-a94d9e274626
# ╟─bb82b077-dfad-4072-ac77-a8cce349e10a
# ╟─a30993b1-b54f-4551-ad0d-90ad7e552f59
# ╠═b58c4563-67e2-4bb7-b4c9-8ced8646b88b
# ╠═c3c7be23-3863-4d58-97c2-9c3270e11371
# ╟─3622b3a0-fe41-4416-be2b-34aabd19c090
# ╟─810e55b1-a1d4-4fcf-84ce-53133d32f853
# ╟─5826f61d-f0b1-4210-8a45-978bd2054585
# ╟─28a12e31-8713-436d-a344-f2a7db9f3c07
# ╟─d17e8dc4-c73e-430e-8807-82bb8d6339e5
# ╠═2c7a5be1-1fcc-47a3-ba47-da49d7306c3b
# ╟─00000000-0000-0000-0000-000000000001
# ╟─00000000-0000-0000-0000-000000000002
